### ISSUE TITLE
Placeholders

### ISSUE THREAD

**Issue by RC1245** [GabiGrin/angular-editable-text#2]
Thanks for the great work Gabi!

One thing I am not sure how to do with your module. How would I get placeholders to display differently from normal header text?

e.g. 

<h1 editable-text="name" class="gg-editable-text" id="name" placeholder="Fill in your name" required/>

This displays the placeholder text as if it was a normal heading until I hover over the Heading. Is there a way to make the placeholder display differently to show it needs to be filled in?

Thanks

**Comment by GabiGrin** [comment]
Added, thanks for the feedback and warm words!

**Comment by RC1245** [comment]
Thanks! worked perfectly!
